apply plugin: 'fabric-loom'
apply plugin: 'com.replaymod.preprocess'
base { archivesName = "$id-$name" }
repositories {
}
dependencies {
    minecraft "com.mojang:minecraft:$name"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:$loader_version"
    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_api_version"
}
loom {
    accessWidenerPath = file "${id}.accesswidener"
    runs {
        server {
            property("mixin.debug.export", "true")
            ideConfigGenerated true
        }
    }
}
JavaVersion javaCompatibility
if (mcVersion < 11700) javaCompatibility = JavaVersion.VERSION_1_8 else if (mcVersion < 11800) javaCompatibility = JavaVersion.VERSION_16 else if (mcVersion < 12005) javaCompatibility = JavaVersion.VERSION_17 else javaCompatibility = JavaVersion.VERSION_21
processResources {
    from "${id}.accesswidener"
    filesMatching('fabric.mod.json') { expand id: id, version: version, minecraft_version: project.name, loader_version: loader_version }
    filesMatching("${id}.mixins.json") { expand java_version: javaCompatibility.getMajorVersion() }
}
java {
    sourceCompatibility = javaCompatibility
    targetCompatibility = javaCompatibility
}
jar { from '../../LICENSE' }

if (mcVersion < 11800) {
    processResources {
        filesMatching('fabric.mod.json') {
            filter { line -> line.replace('"fabric-api"', '"fabric"') }
        }
    }
}
